const categories = [
  { value: 'Alle groepen…', label: 'Alle groepen…' },
  { value: 'Antiek en Kunst', label: 'Antiek en Kunst' },
  { value: 'Audio, Tv en Foto', label: 'Audio, Tv en Foto' },
  { value: "Auto's", label: "Auto's" },
  { value: 'Auto-onderdelen', label: 'Auto-onderdelen' },
  { value: 'Auto diversen', label: 'Auto diversen' },
  { value: 'Boeken', label: 'Boeken' },
  { value: 'Caravans en Kamperen', label: 'Caravans en Kamperen' },
  { value: "Cd's en Dvd's", label: "Cd's en Dvd's" },
  { value: 'Computers en Software', label: 'Computers en Software' },
  { value: 'Contacten en Berichten', label: 'Contacten en Berichten' },
  { value: 'Diensten en Vakmensen', label: 'Diensten en Vakmensen' },
  { value: 'Dieren en Toebehoren', label: 'Dieren en Toebehoren' },
  { value: 'Doe-het-zelf en Verbouw', label: 'Doe-het-zelf en Verbouw' },
  { value: 'Fietsen en Brommers', label: 'Fietsen en Brommers' },
  { value: 'Hobby en Vrije tijd', label: 'Hobby en Vrije tijd' },
  { value: 'Huis en Inrichting', label: 'Huis en Inrichting' },
  { value: 'Huizen en Kamers', label: 'Huizen en Kamers' },
  { value: "Kinderen en Baby's", label: "Kinderen en Baby's" },
  { value: 'Kleding | Dames', label: 'Kleding | Dames' },
  { value: 'Kleding | Heren', label: 'Kleding | Heren' },
  { value: 'Motoren', label: 'Motoren' },
  { value: 'Muziek en Instrumenten', label: 'Muziek en Instrumenten' },
  { value: 'Postzegels en Munten', label: 'Postzegels en Munten' },
  { value: 'Sieraden, Tassen en Uiterlijk', label: 'Sieraden, Tassen en Uiterlijk' },
  { value: 'Spelcomputers en Games', label: 'Spelcomputers en Games' },
  { value: 'Sport en Fitness', label: 'Sport en Fitness' },
  { value: 'Telecommunicatie', label: 'Telecommunicatie' },
  { value: 'Tickets en Kaartjes', label: 'Tickets en Kaartjes' },
  { value: 'Tuin en Terras', label: 'Tuin en Terras' },
  { value: 'Vacatures', label: 'Vacatures' },
  { value: 'Vakantie', label: 'Vakantie' },
  { value: 'Verzamelen', label: 'Verzamelen' },
  { value: 'Watersport en Boten', label: 'Watersport en Boten' },
  { value: 'Witgoed en Apparatuur', label: 'Witgoed en Apparatuur' },
  { value: 'Zakelijke goederen', label: 'Zakelijke goederen' },
  { value: 'Diversen', label: 'Diversen' },
]

module.exports = categories
