export const categories = [
  { text: 'Alle groepen…' },
  { text: 'Antiek en Kunst' },
  { text: 'Audio, Tv en Foto' },
  { text: "Auto's" },
  { text: 'Auto-onderdelen' },
  { text: 'Auto diversen' },
  { text: 'Boeken' },
  { text: 'Caravans en Kamperen' },
  { text: "Cd's en Dvd's" },
  { text: 'Computers en Software' },
  { text: 'Contacten en Berichten' },
  { text: 'Diensten en Vakmensen' },
  { text: 'Dieren en Toebehoren' },
  { text: 'Doe-het-zelf en Verbouw' },
  { text: 'Fietsen en Brommers' },
  { text: 'Hobby en Vrije tijd' },
  { text: 'Huis en Inrichting' },
  { text: 'Huizen en Kamers' },
  { text: "Kinderen en Baby's" },
  { text: 'Kleding | Dames' },
  { text: 'Kleding | Heren' },
  { text: 'Motoren' },
  { text: 'Muziek en Instrumenten' },
  { text: 'Postzegels en Munten' },
  { text: 'Sieraden, Tassen en Uiterlijk' },
  { text: 'Spelcomputers en Games' },
  { text: 'Sport en Fitness' },
  { text: 'Telecommunicatie' },
  { text: 'Tickets en Kaartjes' },
  { text: 'Tuin en Terras' },
  { text: 'Vacatures' },
  { text: 'Vakantie' },
  { text: 'Verzamelen' },
  { text: 'Watersport en Boten' },
  { text: 'Witgoed en Apparatuur' },
  { text: 'Zakelijke goederen' },
  { text: 'Diversen' },
]

export const distances = [
  { text: '< 3 km' },
  { text: '< 5 km' },
  { text: '< 10 km' },
  { text: '< 15 km' },
  { text: '< 25 km' },
  { text: '< 50 km' },
  { text: '< 75 km' },
]
